# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - &build
    id: over
    main: ./cmd/over/main.go
    binary: over
    goos:
      - darwin
      - linux
      - windows
      - freebsd
      - netbsd
      - openbsd
      - dragonfly
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    ignore:
      - goos: openbsd
        goarch: arm64
        # goarm: 6
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X pkg.Version={{.Version}}
      - -X pkg.Commit={{.Commit}}
      - -X pkg.Date={{.Date}}
      - -X pkg.BuiltBy=goreleaser
  - <<: *build
    id: git-over
    main: ./cmd/git-over/main.go
    binary: git-over

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-dev"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
