default_stages: [commit]

repos:
  # Format, lint and test
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.3.5
    hooks:
      - id: go-fmt
      - id: go-imports
        # args: [-local=github.com/Jguer/yay/v10/]
      - id: golangci-lint
      - id: go-unit-tests

  # Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1 # Use the sha or tag you want to point at
    hooks:
      - id: prettier

  # Pre-commit generic hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: check-added-large-files

  # Check Conventional Commit format
  - repo: https://github.com/Woile/commitizen
    rev: v2.17.4
    hooks:
      - id: commitizen
        stages: [commit-msg]
