---
name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2

  pre-commit: # TODO: find a way to merged line and pre-commit with benefit from both
    name: Pre-commit lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/setup-python@v3.1.1
      - uses: Arduino/actions/setup-taskfile@master
      - name: Install golangci-lint
        run: task install:golangci-lint
      - uses: pre-commit/action@v2.0.3

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: Arduino/actions/setup-taskfile@master

      - name: Run Unit tests.
        run: task cover

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out
          flags: unittests

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - lint
      - pre-commit
      - test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: build --snapshot --rm-dist
