---
name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2

  pre-commit:
    name: Pre-commit lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.2

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: Arduino/actions/setup-taskfile@master

      - name: Run Unit tests.
        run: task cover

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          file: ./coverage.out
          flags: unittests

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: build --snapshot --rm-dist
